#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-check_jsonschema
Version  : 0.19.2
Release  : 1
URL      : https://files.pythonhosted.org/packages/c7/f9/c956f3489bff54ffa509787fa6d332ac34f30c95d9cb4c69cf050c133cd6/check-jsonschema-0.19.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/c7/f9/c956f3489bff54ffa509787fa6d332ac34f30c95d9cb4c69cf050c133cd6/check-jsonschema-0.19.2.tar.gz
Summary  : A jsonschema CLI and pre-commit hook
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: pypi-check_jsonschema-bin = %{version}-%{release}
Requires: pypi-check_jsonschema-license = %{version}-%{release}
Requires: pypi-check_jsonschema-python = %{version}-%{release}
Requires: pypi-check_jsonschema-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(click)
BuildRequires : pypi(jsonschema)
BuildRequires : pypi(requests)
BuildRequires : pypi(ruamel.yaml)

%description
[![pypi version](https://img.shields.io/pypi/v/check-jsonschema.svg)](https://pypi.org/project/check-jsonschema/)
[![supported pythons](https://img.shields.io/pypi/pyversions/check-jsonschema.svg)](https://pypi.org/project/check-jsonschema/)
[![build](https://github.com/python-jsonschema/check-jsonschema/actions/workflows/build.yaml/badge.svg)](https://github.com/python-jsonschema/check-jsonschema/actions/workflows/build.yaml)
[![pre-commit.ci status](https://results.pre-commit.ci/badge/github/python-jsonschema/check-jsonschema/main.svg)](https://results.pre-commit.ci/latest/github/python-jsonschema/check-jsonschema/main)
[![readthedocs documentation](https://readthedocs.org/projects/check-jsonschema/badge/?version=stable&style=flat)](https://check-jsonschema.readthedocs.io/en/stable)

%package bin
Summary: bin components for the pypi-check_jsonschema package.
Group: Binaries
Requires: pypi-check_jsonschema-license = %{version}-%{release}

%description bin
bin components for the pypi-check_jsonschema package.


%package license
Summary: license components for the pypi-check_jsonschema package.
Group: Default

%description license
license components for the pypi-check_jsonschema package.


%package python
Summary: python components for the pypi-check_jsonschema package.
Group: Default
Requires: pypi-check_jsonschema-python3 = %{version}-%{release}

%description python
python components for the pypi-check_jsonschema package.


%package python3
Summary: python3 components for the pypi-check_jsonschema package.
Group: Default
Requires: python3-core
Provides: pypi(check_jsonschema)
Requires: pypi(click)
Requires: pypi(jsonschema)
Requires: pypi(requests)
Requires: pypi(ruamel.yaml)

%description python3
python3 components for the pypi-check_jsonschema package.


%prep
%setup -q -n check-jsonschema-0.19.2
cd %{_builddir}/check-jsonschema-0.19.2
pushd ..
cp -a check-jsonschema-0.19.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1669623577
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-check_jsonschema
cp %{_builddir}/check-jsonschema-%{version}/src/check_jsonschema/builtin_schemas/vendor/LICENSE.azure-pipelines %{buildroot}/usr/share/package-licenses/pypi-check_jsonschema/03e1fe6fd0bc6d73c3cd3370d5f0a73c4fcb60d6 || :
cp %{_builddir}/check-jsonschema-%{version}/src/check_jsonschema/builtin_schemas/vendor/LICENSE.schemastore %{buildroot}/usr/share/package-licenses/pypi-check_jsonschema/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/check-jsonschema

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-check_jsonschema/03e1fe6fd0bc6d73c3cd3370d5f0a73c4fcb60d6
/usr/share/package-licenses/pypi-check_jsonschema/2b8b815229aa8a61e483fb4ba0588b8b6c491890

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
